# Generated by Django 5.2.3 on 2025-07-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=255, verbose_name='Nombre de la Ruta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longitud (km)')),
                ('dificultad', models.CharField(choices=[('FACIL', 'Fácil'), ('MODERADO', 'Moderado'), ('DIFICIL', 'Difícil'), ('EXTREMO', 'Extremo')], default='MODERADO', max_length=50, verbose_name='Dificultad')),
                ('duracion_estimada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duración Estimada')),
                ('altitud_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altitud Máxima (m)')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('puntos_interes', models.TextField(blank=True, null=True, verbose_name='Puntos de Interés')),
                ('coordenadas_inicio_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud de Inicio')),
                ('coordenadas_inicio_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud de Inicio')),
                ('coordenadas_fin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud de Fin')),
                ('coordenadas_fin_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud de Fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['nombre_ruta'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserRutaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.usuario')),
            ],
            options={
                'verbose_name': 'Ruta Favorita de Usuario',
                'verbose_name_plural': 'Rutas Favoritas de Usuarios',
                'unique_together': {('usuario', 'ruta')},
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_creadas', to='Aplicacion.usuario', verbose_name='Creada por'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuarios_favoritos',
            field=models.ManyToManyField(related_name='rutas_favoritas', through='Aplicacion.UserRutaFavorita', to='Aplicacion.usuario', verbose_name='Marcada como Favorita por'),
        ),
    ]
