# Generated by Django 5.2.3 on 2025-08-05 20:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=255, verbose_name='Nombre de la Ruta')),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rutas_imagenes/')),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longitud (km)')),
                ('dificultad', models.CharField(choices=[('FACIL', 'Fácil'), ('MODERADO', 'Moderado'), ('DIFICIL', 'Difícil'), ('EXTREMO', 'Extremo')], default='MODERADO', max_length=50, verbose_name='Dificultad')),
                ('duracion_estimada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duración Estimada')),
                ('altitud_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altitud Máxima (m)')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('puntos_interes', models.TextField(blank=True, null=True, verbose_name='Puntos de Interés')),
                ('coordenadas_inicio_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud de Inicio')),
                ('coordenadas_inicio_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud de Inicio')),
                ('coordenadas_fin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud de Fin')),
                ('coordenadas_fin_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud de Fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['nombre_ruta'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRutaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorita_por_usuarios', to='Aplicacion.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritas_intermedias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta Favorita de Usuario',
                'verbose_name_plural': 'Rutas Favoritas de Usuarios',
                'unique_together': {('usuario', 'ruta')},
            },
        ),
        migrations.CreateModel(
            name='RutaRecorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuarios_favoritos',
            field=models.ManyToManyField(related_name='rutas_favoritas', through='Aplicacion.UserRutaFavorita', to=settings.AUTH_USER_MODEL, verbose_name='Marcada como Favorita por'),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=500)),
                ('imagen', models.ImageField(upload_to='publicaciones/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Aplicacion.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
