# Generated by Django 5.2.3 on 2025-08-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='correo_electronico',
        ),
    ]
