# Generated by Django 5.2.3 on 2025-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rutas_imagenes/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
