# Generated by Django 5.2.3 on 2025-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_publicacion_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
