# Generated by Django 5.2.3 on 2025-08-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_ruta_vistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='usuarios_favoritos',
            field=models.ManyToManyField(related_name='rutas_favoritas_m2m', through='Aplicacion.UserRutaFavorita', to=settings.AUTH_USER_MODEL, verbose_name='Marcada como Favorita por'),
        ),
        migrations.AlterField(
            model_name='userrutafavorita',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorita_por_usuarios', to='Aplicacion.ruta'),
        ),
        migrations.AlterField(
            model_name='userrutafavorita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_rutas_favoritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
