# Generated by Django 5.2.3 on 2025-08-04 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_alter_ruta_usuarios_favoritos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='usuarios_favoritos',
            field=models.ManyToManyField(related_name='rutas_favoritas', through='Aplicacion.UserRutaFavorita', to=settings.AUTH_USER_MODEL, verbose_name='Marcada como Favorita por'),
        ),
        migrations.AlterField(
            model_name='userrutafavorita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritas_intermedias', to=settings.AUTH_USER_MODEL),
        ),
    ]
